{
 "title": "Dell iDRAC SNMP  Exporter Dashboard for VictoriaMetrics",
 "description": "戴尔物理服务器 iDRAC 监控面板",
 "tags": [
  "VictoriaMetrics",
  "dell",
  "snmp_exporter"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "job",
    "label": "任务",
    "query": {
     "query": "label_values(globalSystemStatus,job)"
    }
   },
   {
    "name": "region",
    "label": "区域",
    "query": {
     "query": "label_values(globalSystemStatus{job=~\"$job\"},region)"
    }
   },
   {
    "name": "brand",
    "label": "品牌",
    "query": {
     "query": "label_values(globalSystemStatus{job=~\"$job\", region=~\"$region\"},brand)"
    }
   },
   {
    "name": "role",
    "label": "角色",
    "query": {
     "query": "label_values(globalSystemStatus{job=~\"$job\", region=~\"$region\", brand=~\"$brand\"},role)"
    }
   },
   {
    "name": "device_ip",
    "label": "实例",
    "query": {
     "query": "query_result(count by (instance) (count_over_time(globalSystemStatus{job=~\"$job\", region=~\"$region\", brand=~\"$brand\", role=~\"$role\"}[$__range])))"
    }
   },
   {
    "name": "total",
    "label": "物理机总数",
    "query": {
     "query": "query_result(count(globalSystemStatus{job=~\"$job\", region=~\"$region\", brand=~\"$brand\", role=~\"$role\"}))"
    }
   },
   { "name": "Filters", "label": "筛选" }
  ]
 },
 "panels": [
  {
   "title": "系统信息：总数【$total】",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "系统信息",
     "type": "table",
     "description": "服务器系统基础信息",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 1 },
     "targets": [
      {
       "expr": "up{job=~\"$job\", region=~\"$region\", brand=~\"$brand\", role=~\"$role\"}",
       "legendFormat": "__auto"
      },
      {
       "expr": "systemServiceTag{job=~\"$job\", region=~\"$region\", brand=~\"$brand\", role=~\"$role\"}",
       "legendFormat": "__auto"
      },
      {
       "expr": "systemExpressServiceCode{job=~\"$job\", region=~\"$region\", brand=~\"$brand\", role=~\"$role\"}",
       "legendFormat": "__auto"
      },
      {
       "expr": "racFirmwareVersion{job=~\"$job\", region=~\"$region\", brand=~\"$brand\", role=~\"$role\"}",
       "legendFormat": "__auto"
      },
      {
       "expr": "racShortName{job=~\"$job\", region=~\"$region\", brand=~\"$brand\", role=~\"$role\"}",
       "legendFormat": "__auto"
      },
      {
       "expr": "systemModelName{job=~\"$job\", region=~\"$region\", brand=~\"$brand\", role=~\"$role\"}",
       "legendFormat": "__auto"
      },
      {
       "expr": "systemOSName{job=~\"$job\", region=~\"$region\", brand=~\"$brand\", role=~\"$role\"}",
       "legendFormat": "__auto"
      },
      {
       "expr": "systemOSVersion{job=~\"$job\", region=~\"$region\", brand=~\"$brand\", role=~\"$role\"}",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  { "title": "组件状态", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 } },
  {
   "title": "系统启动时间（天）",
   "type": "stat",
   "description": "戴尔物理服务器系统启动时间信息",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "systemPowerUpTime{job=~\"$job\", region=~\"$region\", brand=~\"$brand\", role=~\"$role\", instance=\"$device_ip\"} / 3600 / 24",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "系统电源状态",
   "type": "stat",
   "description": "戴尔物理服务器全局系统电源状态信息",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 2 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "systemPowerState{job=~\"$job\", region=~\"$region\", brand=~\"$brand\", role=~\"$role\", instance=\"$device_ip\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "全局系统状态",
   "type": "stat",
   "description": "戴尔物理服务器全局系统状态信息",
   "gridPos": { "h": 4, "w": 3, "x": 8, "y": 2 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "globalSystemStatus{job=~\"$job\", region=~\"$region\", brand=~\"$brand\", role=~\"$role\", instance=\"$device_ip\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "全局存储状态",
   "type": "stat",
   "description": "戴尔物理服务器全局存储状态信息",
   "gridPos": { "h": 4, "w": 4, "x": 11, "y": 2 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "globalStorageStatus{job=~\"$job\", region=~\"$region\", brand=~\"$brand\", role=~\"$role\", instance=\"$device_ip\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "BIOS状态",
   "type": "table",
   "description": "戴尔物理服务器设备BIOS状态信息",
   "gridPos": { "h": 4, "w": 9, "x": 15, "y": 2 },
   "targets": [
    {
     "expr": "systemBIOSStatus{job=~\"$job\", region=~\"$region\", brand=~\"$brand\", role=~\"$role\", instance=\"$device_ip\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "systemBIOSStateSettings{job=~\"$job\", region=~\"$region\", brand=~\"$brand\", role=~\"$role\", instance=\"$device_ip\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "systemBIOSVersionName{job=~\"$job\", region=~\"$region\", brand=~\"$brand\", role=~\"$role\", instance=\"$device_ip\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "事件日志条目数",
   "type": "timeseries",
   "description": "戴尔物理服务器事件日志中的条目数",
   "gridPos": { "h": 5, "w": 7, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "numEventLogEntries{job=~\"$job\", region=~\"$region\", brand=~\"$brand\", role=~\"$role\", instance=\"$device_ip\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "系统使用功率",
   "type": "timeseries",
   "description": "物理机使用功率",
   "gridPos": { "h": 5, "w": 8, "x": 7, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "expr": "amperageProbeReading{job=~\"$job\", region=~\"$region\", brand=~\"$brand\", role=~\"$role\", instance=\"$device_ip\"}",
     "legendFormat": "{{amperageProbeLocationName}}"
    }
   ]
  },
  {
   "title": "LCD状态",
   "type": "stat",
   "description": "戴尔物理服务器设备LCD状态信息",
   "gridPos": { "h": 5, "w": 9, "x": 15, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "systemLCDStatus{job=~\"$job\", region=~\"$region\", brand=~\"$brand\", role=~\"$role\", instance=\"$device_ip\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "物理机当前使用功率",
   "type": "stat",
   "description": "物理机当前使用功率",
   "gridPos": { "h": 5, "w": 9, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "amperageProbeReading{job=~\"$job\", region=~\"$region\", brand=~\"$brand\", role=~\"$role\", instance=\"$device_ip\"}",
     "legendFormat": "{{amperageProbeLocationName}}"
    }
   ]
  },
  {
   "title": "Raid状态信息",
   "type": "table",
   "description": "戴尔物理服务器设备Raid状态信息",
   "gridPos": { "h": 5, "w": 15, "x": 9, "y": 11 },
   "targets": [
    {
     "expr": "virtualDiskState{job=~\"$job\", region=~\"$region\", brand=~\"$brand\", role=~\"$role\", instance=\"$device_ip\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "virtualDiskSizeInMB{job=~\"$job\", region=~\"$region\", brand=~\"$brand\", role=~\"$role\", instance=\"$device_ip\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "virtualDiskDisplayName{job=~\"$job\", region=~\"$region\", brand=~\"$brand\", role=~\"$role\", instance=\"$device_ip\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "virtualDiskLayout{job=~\"$job\", region=~\"$region\", brand=~\"$brand\", role=~\"$role\", instance=\"$device_ip\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "virtualDiskAvailableProtocols{job=~\"$job\", region=~\"$region\", brand=~\"$brand\", role=~\"$role\", instance=\"$device_ip\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "virtualDiskStripeSize{job=~\"$job\", region=~\"$region\", brand=~\"$brand\", role=~\"$role\", instance=\"$device_ip\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "virtualDiskMediaType{job=~\"$job\", region=~\"$region\", brand=~\"$brand\", role=~\"$role\", instance=\"$device_ip\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "风扇状态",
   "type": "table",
   "description": "戴尔物理服务器风扇状态信息",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "coolingDeviceStateSettings{job=~\"$job\", region=~\"$region\", brand=~\"$brand\", role=~\"$role\", instance=\"$device_ip\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "coolingDeviceStatus{job=~\"$job\", region=~\"$region\", brand=~\"$brand\", role=~\"$role\", instance=\"$device_ip\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "coolingDeviceReading{job=~\"$job\", region=~\"$region\", brand=~\"$brand\", role=~\"$role\", instance=\"$device_ip\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "固件状态",
   "type": "table",
   "description": "戴尔物理服务器固件状态信息",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "firmwareStateSettings{job=~\"$job\", region=~\"$region\", brand=~\"$brand\", role=~\"$role\", instance=\"$device_ip\"} * on(instance) group_left(systemServiceTag) systemServiceTag{systemServiceTag!=\"\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "firmwareStatus{job=~\"$job\", region=~\"$region\", brand=~\"$brand\", role=~\"$role\", instance=\"$device_ip\"} * on(instance) group_left(systemServiceTag) systemServiceTag{systemServiceTag!=\"\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "侵入设备状态",
   "type": "table",
   "description": "戴尔物理服务器侵入设备状态信息",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "intrusionStateSettings{job=~\"$job\", region=~\"$region\", brand=~\"$brand\", role=~\"$role\", instance=\"$device_ip\"} * on(instance) group_left(systemServiceTag) systemServiceTag{systemServiceTag!=\"\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "intrusionStatus{job=~\"$job\", region=~\"$region\", brand=~\"$brand\", role=~\"$role\", instance=\"$device_ip\"} * on(instance) group_left(systemServiceTag) systemServiceTag{systemServiceTag!=\"\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "电源设备状态",
   "type": "table",
   "description": "戴尔物理服务器电源状态信息",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 24 },
   "targets": [
    {
     "expr": "powerSupplyStateSettingsUnique{job=~\"$job\", region=~\"$region\", brand=~\"$brand\", role=~\"$role\", instance=\"$device_ip\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "powerSupplyStatus{job=~\"$job\", region=~\"$region\", brand=~\"$brand\", role=~\"$role\", instance=\"$device_ip\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "powerSupplyOutputWatts{job=~\"$job\", region=~\"$region\", brand=~\"$brand\", role=~\"$role\", instance=\"$device_ip\"} / 10",
     "legendFormat": "__auto"
    },
    {
     "expr": "powerSupplyRatedInputWattage{job=~\"$job\", region=~\"$region\", brand=~\"$brand\", role=~\"$role\", instance=\"$device_ip\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "powerSupplyMaximumInputVoltage{job=~\"$job\", region=~\"$region\", brand=~\"$brand\", role=~\"$role\", instance=\"$device_ip\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "powerSupplyCurrentInputVoltage{job=~\"$job\", region=~\"$region\", brand=~\"$brand\", role=~\"$role\", instance=\"$device_ip\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "温度传感器状态",
   "type": "table",
   "description": "戴尔物理服务器温度传感器状态信息",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 29 },
   "targets": [
    {
     "expr": "temperatureProbeStateSettings{job=~\"$job\", region=~\"$region\", brand=~\"$brand\", role=~\"$role\", instance=\"$device_ip\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "temperatureProbeReading{job=~\"$job\", region=~\"$region\", brand=~\"$brand\", role=~\"$role\", instance=\"$device_ip\"} / 10",
     "legendFormat": "__auto"
    },
    {
     "expr": "temperatureProbeUpperCriticalThreshold{job=~\"$job\", region=~\"$region\", brand=~\"$brand\", role=~\"$role\", instance=\"$device_ip\"} / 10",
     "legendFormat": "__auto"
    },
    {
     "expr": "temperatureProbeStatus{job=~\"$job\", region=~\"$region\", brand=~\"$brand\", role=~\"$role\", instance=\"$device_ip\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "PCI设备状态",
   "type": "table",
   "description": "戴尔物理服务器PCI设备状态信息",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 29 },
   "targets": [
    {
     "expr": "pCIDeviceStateSettings{job=~\"$job\", region=~\"$region\", brand=~\"$brand\", role=~\"$role\", instance=\"$device_ip\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "pCIDeviceStatus{job=~\"$job\", region=~\"$region\", brand=~\"$brand\", role=~\"$role\", instance=\"$device_ip\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "pCIDeviceManufacturerName{job=~\"$job\", region=~\"$region\", brand=~\"$brand\", role=~\"$role\", instance=\"$device_ip\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "pCIDeviceDescriptionName{job=~\"$job\", region=~\"$region\", brand=~\"$brand\", role=~\"$role\", instance=\"$device_ip\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "内存信息",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 34 },
   "collapsed": true,
   "panels": [
    {
     "title": "内存状态",
     "type": "stat",
     "description": "戴尔物理服务器内存状态信息",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 359 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "memoryDeviceStatus{job=~\"$job\", region=~\"$region\", brand=~\"$brand\", role=~\"$role\", instance=\"$device_ip\"}",
       "legendFormat": "{{memoryDeviceFQDD}}"
      }
     ]
    },
    {
     "title": "内存信息",
     "type": "table",
     "description": "戴尔物理服务器内存信息",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 359 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "memoryDeviceStateSettings{job=~\"$job\", region=~\"$region\", brand=~\"$brand\", role=~\"$role\", instance=\"$device_ip\"}",
       "legendFormat": "__auto"
      },
      {
       "expr": "memoryDeviceStatus{job=~\"$job\", region=~\"$region\", brand=~\"$brand\", role=~\"$role\", instance=\"$device_ip\"}",
       "legendFormat": "__auto"
      },
      {
       "expr": "memoryDeviceManufacturerName{job=~\"$job\", region=~\"$region\", brand=~\"$brand\", role=~\"$role\", instance=\"$device_ip\"}",
       "legendFormat": "__auto"
      },
      {
       "expr": "memoryDeviceCurrentOperatingSpeed{job=~\"$job\", region=~\"$region\", brand=~\"$brand\", role=~\"$role\", instance=\"$device_ip\"}",
       "legendFormat": "__auto"
      },
      {
       "expr": "memoryDeviceSpeed{job=~\"$job\", region=~\"$region\", brand=~\"$brand\", role=~\"$role\", instance=\"$device_ip\"}",
       "legendFormat": "__auto"
      },
      {
       "expr": "memoryDeviceSize{job=~\"$job\", region=~\"$region\", brand=~\"$brand\", role=~\"$role\", instance=\"$device_ip\"}",
       "legendFormat": "__auto"
      },
      {
       "expr": "memoryDeviceSerialNumberName{job=~\"$job\", region=~\"$region\", brand=~\"$brand\", role=~\"$role\", instance=\"$device_ip\"}",
       "legendFormat": "__auto"
      },
      {
       "expr": "memoryDeviceType{job=~\"$job\", region=~\"$region\", brand=~\"$brand\", role=~\"$role\", instance=\"$device_ip\"}",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "硬盘信息",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 35 },
   "collapsed": true,
   "panels": [
    {
     "title": "硬盘状态",
     "type": "stat",
     "description": "戴尔物理服务器硬盘状态信息",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 360 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "physicalDiskState{job=~\"$job\", region=~\"$region\", brand=~\"$brand\", role=~\"$role\", instance=\"$device_ip\"}",
       "legendFormat": "{{physicalDiskName}}"
      }
     ]
    },
    {
     "title": "硬盘状态信息",
     "type": "table",
     "description": "戴尔物理服务器硬盘状态信息",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 360 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "physicalDiskState{job=~\"$job\", region=~\"$region\", brand=~\"$brand\", role=~\"$role\", instance=\"$device_ip\"}",
       "legendFormat": "__auto"
      },
      {
       "expr": "physicalDiskSmartAlertIndication{job=~\"$job\", region=~\"$region\", brand=~\"$brand\", role=~\"$role\", instance=\"$device_ip\"}",
       "legendFormat": "__auto"
      },
      {
       "expr": "physicalDiskSpareState{job=~\"$job\", region=~\"$region\", brand=~\"$brand\", role=~\"$role\", instance=\"$device_ip\"}",
       "legendFormat": "__auto"
      },
      {
       "expr": "physicalDiskOperationalState{job=~\"$job\", region=~\"$region\", brand=~\"$brand\", role=~\"$role\", instance=\"$device_ip\"}",
       "legendFormat": "__auto"
      },
      {
       "expr": "physicalDiskProgress{job=~\"$job\", region=~\"$region\", brand=~\"$brand\", role=~\"$role\", instance=\"$device_ip\"}",
       "legendFormat": "__auto"
      },
      {
       "expr": "physicalDiskRemainingRatedWriteEndurance{job=~\"$job\", region=~\"$region\", brand=~\"$brand\", role=~\"$role\", instance=\"$device_ip\"}",
       "legendFormat": "__auto"
      },
      {
       "expr": "physicalDiskSecurityStatus{job=~\"$job\", region=~\"$region\", brand=~\"$brand\", role=~\"$role\", instance=\"$device_ip\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "硬盘信息",
     "type": "table",
     "description": "戴尔物理服务器硬盘信息",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 492 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "physicalDiskBusType{job=~\"$job\", region=~\"$region\", brand=~\"$brand\", role=~\"$role\", instance=\"$device_ip\"}",
       "legendFormat": "__auto"
      },
      {
       "expr": "physicalDiskBlockSizeInBytes{job=~\"$job\", region=~\"$region\", brand=~\"$brand\", role=~\"$role\", instance=\"$device_ip\"}",
       "legendFormat": "__auto"
      },
      {
       "expr": "physicalDiskManufacturer{job=~\"$job\", region=~\"$region\", brand=~\"$brand\", role=~\"$role\", instance=\"$device_ip\"}",
       "legendFormat": "__auto"
      },
      {
       "expr": "physicalDiskFormFactor{job=~\"$job\", region=~\"$region\", brand=~\"$brand\", role=~\"$role\", instance=\"$device_ip\"}",
       "legendFormat": "__auto"
      },
      {
       "expr": "physicalDiskMediaType{job=~\"$job\", region=~\"$region\", brand=~\"$brand\", role=~\"$role\", instance=\"$device_ip\"}",
       "legendFormat": "__auto"
      },
      {
       "expr": "physicalDiskT10PICapability{job=~\"$job\", region=~\"$region\", brand=~\"$brand\", role=~\"$role\", instance=\"$device_ip\"}",
       "legendFormat": "__auto"
      },
      {
       "expr": "physicalDiskProductID{job=~\"$job\", region=~\"$region\", brand=~\"$brand\", role=~\"$role\", instance=\"$device_ip\"}",
       "legendFormat": "__auto"
      },
      {
       "expr": "physicalDiskProtocolVersion{job=~\"$job\", region=~\"$region\", brand=~\"$brand\", role=~\"$role\", instance=\"$device_ip\"}",
       "legendFormat": "__auto"
      },
      {
       "expr": "physicalDiskRevision{job=~\"$job\", region=~\"$region\", brand=~\"$brand\", role=~\"$role\", instance=\"$device_ip\"}",
       "legendFormat": "__auto"
      },
      {
       "expr": "physicalDiskSerialNo{job=~\"$job\", region=~\"$region\", brand=~\"$brand\", role=~\"$role\", instance=\"$device_ip\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "硬盘速率信息",
     "type": "table",
     "description": "戴尔物理服务器硬盘速率信息",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 492 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "physicalDiskCapacityInMB{job=~\"$job\", region=~\"$region\", brand=~\"$brand\", role=~\"$role\", instance=\"$device_ip\"}",
       "legendFormat": "__auto"
      },
      {
       "expr": "physicalDiskUsedSpaceInMB{job=~\"$job\", region=~\"$region\", brand=~\"$brand\", role=~\"$role\", instance=\"$device_ip\"}",
       "legendFormat": "__auto"
      },
      {
       "expr": "physicalDiskCapableSpeed{job=~\"$job\", region=~\"$region\", brand=~\"$brand\", role=~\"$role\", instance=\"$device_ip\"}",
       "legendFormat": "__auto"
      },
      {
       "expr": "physicalDiskBusType{job=~\"$job\", region=~\"$region\", brand=~\"$brand\", role=~\"$role\", instance=\"$device_ip\"}",
       "legendFormat": "__auto"
      },
      {
       "expr": "physicalDiskNegotiatedSpeed{job=~\"$job\", region=~\"$region\", brand=~\"$brand\", role=~\"$role\", instance=\"$device_ip\"}",
       "legendFormat": "__auto"
      },
      {
       "expr": "physicalDiskPCIeNegotiatedLinkWidth{job=~\"$job\", region=~\"$region\", brand=~\"$brand\", role=~\"$role\", instance=\"$device_ip\"}",
       "legendFormat": "__auto"
      },
      {
       "expr": "physicalDiskPCIeCapableLinkWidth{job=~\"$job\", region=~\"$region\", brand=~\"$brand\", role=~\"$role\", instance=\"$device_ip\"}",
       "legendFormat": "__auto"
      },
      {
       "expr": "physicalDiskProtocolVersion{job=~\"$job\", region=~\"$region\", brand=~\"$brand\", role=~\"$role\", instance=\"$device_ip\"}",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "网卡信息",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 36 },
   "collapsed": true,
   "panels": [
    {
     "title": "网卡信息",
     "type": "table",
     "description": "戴尔物理服务器网卡信息",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 361 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "networkDeviceStatus{job=~\"$job\", region=~\"$region\", brand=~\"$brand\", role=~\"$role\", instance=\"$device_ip\"}",
       "legendFormat": "__auto"
      },
      {
       "expr": "networkDeviceConnectionStatus{job=~\"$job\", region=~\"$region\", brand=~\"$brand\", role=~\"$role\", instance=\"$device_ip\"}",
       "legendFormat": "__auto"
      },
      {
       "expr": "networkDevicePermanentMACAddress{job=~\"$job\", region=~\"$region\", brand=~\"$brand\", role=~\"$role\", instance=\"$device_ip\"}",
       "legendFormat": "__auto"
      },
      {
       "expr": "networkDeviceProductName{job=~\"$job\", region=~\"$region\", brand=~\"$brand\", role=~\"$role\", instance=\"$device_ip\"}",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "控制器信息",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 37 },
   "collapsed": true,
   "panels": [
    {
     "title": "存储控制器状态",
     "type": "table",
     "description": "戴尔物理服务器存储控制器信息",
     "gridPos": { "h": 4, "w": 24, "x": 0, "y": 110 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "controllerComponentStatus{job=~\"$job\", region=~\"$region\", brand=~\"$brand\", role=~\"$role\", instance=\"$device_ip\"}",
       "legendFormat": "__auto"
      },
      {
       "expr": "controllerRollUpStatus{job=~\"$job\", region=~\"$region\", brand=~\"$brand\", role=~\"$role\", instance=\"$device_ip\"}",
       "legendFormat": "__auto"
      },
      {
       "expr": "controllerDriverVersion{job=~\"$job\", region=~\"$region\", brand=~\"$brand\", role=~\"$role\", instance=\"$device_ip\"}",
       "legendFormat": "__auto"
      },
      {
       "expr": "controllerDisplayName{job=~\"$job\", region=~\"$region\", brand=~\"$brand\", role=~\"$role\", instance=\"$device_ip\"}",
       "legendFormat": "__auto"
      },
      {
       "expr": "controllerFWVersion{job=~\"$job\", region=~\"$region\", brand=~\"$brand\", role=~\"$role\", instance=\"$device_ip\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "存储控制器性能信息",
     "type": "table",
     "description": "戴尔物理服务器存储控制器性能信息",
     "gridPos": { "h": 4, "w": 24, "x": 0, "y": 146 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "controllerCacheSizeInMB{job=~\"$job\", region=~\"$region\", brand=~\"$brand\", role=~\"$role\", instance=\"$device_ip\"}",
       "legendFormat": "__auto"
      },
      {
       "expr": "controllerSecurityStatus{job=~\"$job\", region=~\"$region\", brand=~\"$brand\", role=~\"$role\", instance=\"$device_ip\"}",
       "legendFormat": "__auto"
      },
      {
       "expr": "controllerLoadBalanceSetting{job=~\"$job\", region=~\"$region\", brand=~\"$brand\", role=~\"$role\", instance=\"$device_ip\"}",
       "legendFormat": "__auto"
      },
      {
       "expr": "controllerMaxCapSpeed{job=~\"$job\", region=~\"$region\", brand=~\"$brand\", role=~\"$role\", instance=\"$device_ip\"}",
       "legendFormat": "__auto"
      },
      {
       "expr": "controllerDisplayName{job=~\"$job\", region=~\"$region\", brand=~\"$brand\", role=~\"$role\", instance=\"$device_ip\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "存储控制器速率信息",
     "type": "table",
     "description": "戴尔物理服务器存储控制器速率信息",
     "gridPos": { "h": 4, "w": 24, "x": 0, "y": 150 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "controllerRebuildRate{job=~\"$job\", region=~\"$region\", brand=~\"$brand\", role=~\"$role\", instance=\"$device_ip\"}",
       "legendFormat": "__auto"
      },
      {
       "expr": "controllerReconstructRate{job=~\"$job\", region=~\"$region\", brand=~\"$brand\", role=~\"$role\", instance=\"$device_ip\"}",
       "legendFormat": "__auto"
      },
      {
       "expr": "controllerPatrolReadRate{job=~\"$job\", region=~\"$region\", brand=~\"$brand\", role=~\"$role\", instance=\"$device_ip\"}",
       "legendFormat": "__auto"
      },
      {
       "expr": "controllerBGIRate{job=~\"$job\", region=~\"$region\", brand=~\"$brand\", role=~\"$role\", instance=\"$device_ip\"}",
       "legendFormat": "__auto"
      },
      {
       "expr": "controllerCheckConsistencyRate{job=~\"$job\", region=~\"$region\", brand=~\"$brand\", role=~\"$role\", instance=\"$device_ip\"}",
       "legendFormat": "__auto"
      },
      {
       "expr": "controllerDisplayName{job=~\"$job\", region=~\"$region\", brand=~\"$brand\", role=~\"$role\", instance=\"$device_ip\"}",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "FRU信息",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 38 },
   "collapsed": true,
   "panels": [
    {
     "title": "FRU信息",
     "type": "table",
     "description": "戴尔物理服务器FRU信息",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 111 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "fruInformationStatus{job=~\"$job\", region=~\"$region\", brand=~\"$brand\", role=~\"$role\", instance=\"$device_ip\"}",
       "legendFormat": "__auto"
      },
      {
       "expr": "fruManufacturerName{job=~\"$job\", region=~\"$region\", brand=~\"$brand\", role=~\"$role\", instance=\"$device_ip\"}",
       "legendFormat": "__auto"
      },
      {
       "expr": "fruSerialNumberName{job=~\"$job\", region=~\"$region\", brand=~\"$brand\", role=~\"$role\", instance=\"$device_ip\"}",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "PCI组件信息",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 39 },
   "collapsed": true,
   "panels": [
    {
     "title": "PCI信息",
     "type": "table",
     "description": "戴尔物理服务器PCI信息",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 112 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "pCIDeviceStateSettings{job=~\"$job\", region=~\"$region\", brand=~\"$brand\", role=~\"$role\", instance=\"$device_ip\"}",
       "legendFormat": "__auto"
      },
      {
       "expr": "pCIDeviceStatus{job=~\"$job\", region=~\"$region\", brand=~\"$brand\", role=~\"$role\", instance=\"$device_ip\"}",
       "legendFormat": "__auto"
      },
      {
       "expr": "pCIDeviceManufacturerName{job=~\"$job\", region=~\"$region\", brand=~\"$brand\", role=~\"$role\", instance=\"$device_ip\"}",
       "legendFormat": "__auto"
      },
      {
       "expr": "pCIDeviceDescriptionName{job=~\"$job\", region=~\"$region\", brand=~\"$brand\", role=~\"$role\", instance=\"$device_ip\"}",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  }
 ]
}